# Generated by Django 4.0.5 on 2022-06-24 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DB_TEST', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='beeline_test2/docs')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Hive-example', max_length=128)),
                ('serviceType', models.CharField(default='Hive', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default.domain_ess_nfs_dm', max_length=128)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beeline_test2.database')),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beeline_test2.service'),
        ),
        migrations.CreateModel(
            name='ap_ap_invoices_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(default='Table description', max_length=128)),
                ('Field', models.CharField(max_length=128)),
                ('Table_Name', models.CharField(max_length=128)),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beeline_test2.service')),
            ],
        ),
    ]
