# Generated by Django 4.0.5 on 2022-06-27 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beeline_test2', '0009_alter_excel_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Excel',
            new_name='ExcelModel',
        ),
    ]
